### ISSUE TITLE
GitBook Community in Google+

### ISSUE THREAD

**Issue by aleen42** [mizunashi-mana/gitbook-plugin-forkmegithub#2]
Hi mizunashi-mana,

I am Aleen (https://github.com/aleen42) , and the founder of GitBook Community in Google+: https://plus.google.com/communities/110696788983472771007, which aims to sharing books or plugins of GitBook, talking anything about it as well. Here I am sincerely inviting you to join us.  :punch:

**Comment by mizunashi-mana** [comment]
@aleen42 Hi,

Thanks for good project.  I joined this community.  When I have more time, I try to write some.

**Comment by aleen42** [comment]
@mizunashi-mana yup~ thx~
